version: "3.4"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - 8888:8888
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    links:
      - redis
    depends_on:
      - redis

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENDPOINT=http://127.0.0.1:8888
