version: "3.4"
services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - 8888:8888

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENDPOINT=http://127.0.0.1:8888
