export const MIN_PERSON_TRANSACTIONS = 1;
export const MAX_PERSON_TRANSACTIONS = 3;
export const MIN_INTERVAL_NEW_PERSON = 2000;
export const MAX_INTERVAL_NEW_PERSON = 4000;

export const TIME_FOR_A_TRANSACTION = 1000;

export const QUEUE_NAME = 'ATM_QUEUE';

export const JOB_TYPES = {
  ADD_ATM: 'ADD_ATM',
  ADD_PERSON: 'ADD_PERSON',
  PROCESS_TRANSACTIONS: 'PROCESS_TRANSACTIONS',
};
